BookReviewer/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.new_login.urls', namespace='users')),
    url(r'^reviewer/', include('apps.bookRev.urls', namespace='books')),
]

apps/bookRev/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^books$', views.index, name ='index'),
    url(r'^show/(?P<id>\d+)$', views.show, name='show'),
    url(r'^user/(?P<id>\d+)$', views.user, name='user'),
    url(r'^addForm$', views.addForm, name='addForm'),
    url(r'^logOut$', views.logOut, name='logOut'),
    url(r'^addBook$', views.add_Book_Author_Review, name='newBook'),
    url(r'^addReview/(?P<id>\d+)$', views.addReview, name='addReview'),
]

apps/bookRev/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.exceptions import ObjectDoesNotExist
from ..new_login.models import User

class allManager(models.Manager):
    #must handle all validations in one
    #since we only want entries to be created in the DB if
    #ALL pass, THEN route to respective addfunctions and return
    #IMPORTANT: get returns error if it can't find, filter returns array
    def validateForm(self, data):
        errors = []
        response = {}
        #author validation
        if len(data['author_name']) < 1:
            errors.append("Must add an Author")

        existing_author = Authors.authorMgr.filter(name=data['author_name'])
        #filter returns array, empty array is 'falsey', thus if not 'falsey'
        # returns True, else if not 'true' (true means array has stuff)
        if existing_author:
            errors.append("Author already exists, Select from Menu")

        #book validation
        if len(data['title']) < 1:
            errors.append("Book Title Cannot be Blank!")
        existing_book = Books.bookMgr.filter(title=data['title'])
        if existing_book:
            errors.append("Book already exists, add a new Review")

        #Review Validation
        if len(data['review']) < 1:
            errors.append("Review Cannot Be Blank!")
        #done validations, if errors, return errors, else create entries
        if len(errors) > 0:
            response['passed'] = False
            response['errors'] = errors
            return response
        else:
            response['passed'] = True
            return response

    def addAuthor(self, data):
        new_author = self.create(name=data['author_name'])
        return new_author

    def addBook(self, data):
        author = Authors.authorMgr.get(name=data['author_name'])
        new_book =self.create(title=data['title'], author=author)
        return new_book

    def addReview(self, data, user_id, book_id):
        print data
        print book_id
        print user_id
        #user_id is request.session['user_id'] from views
        book = Books.bookMgr.get(id=book_id)
        user = User.objects.get(id=user_id)
        new_review = self.create(review=data['review'], rating=data['rating'], book=book, user=user)
        return new_review

    # def addAnotherReview(self, data, user_id):
    #     book = Books.bookMgr.get(id=data['book_id'])
    #     user = User.objects.get(id=user_id)
    #     new_review = Reviews.reviewMgr.create(review=data['add_review'], rating=data['rating'], book=book, user=user)
    #     return new_review

# Create your models here.
class Authors(models.Model):
    name = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    authorMgr = allManager()

class Books(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(Authors)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    bookMgr = allManager()

class Reviews(models.Model):
    review = models.TextField(max_length=1000)
    rating = models.IntegerField()
    book = models.ForeignKey(Books, related_name="userBooks")
    user = models.ForeignKey(User, related_name= "userReviews")
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now=True)
    reviewMgr = allManager()

apps/bookRev/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from .models import Books, Reviews, Authors, allManager
from ..new_login.models import User

# Create your views here.
def index(request):
    this_user = User.objects.get(id=request.session['id'])
    recent_reviews = Reviews.reviewMgr.all().order_by('-created_at')[:3]
    all_books = Books.bookMgr.all()
    all_authors = Authors.authorMgr.all()
    for i in recent_reviews:
        print i.created_at
    context={
        'this_user':this_user,
        'authors':all_authors,
        'recent_reviews': recent_reviews,
        'all_books': all_books
    }
    return render(request, 'bookRev/bookIndex.html', context)

def addForm(request):
    all_authors = Authors.authorMgr.all()
    print all_authors
    context = {
        'authors':all_authors
    }
    return render(request, 'bookRev/addBook.html', context)

def show(request, id):
    result = Books.bookMgr.get(id=id)
    reviews = Reviews.reviewMgr.filter(book=id)
    context = {
        'this_book': result,
        'all_reviews':reviews
    }
    return render(request, 'bookRev/show.html', context)

def user(request, id):
    result = User.objects.get(id=id)
    reviews = Reviews.reviewMgr.filter(user=id)
    print reviews
    context = {
        'this_user': result,
        "user_reviews": reviews
    }
    return render(request, 'bookRev/user.html', context)

def add_Book_Author_Review(request):
    if request.method == 'POST':
        #submits form info to validate all before adding entries
        manager = allManager()
        validateAll = manager.validateForm(request.POST)

        if validateAll['passed']:
            #adds each individual piece if they all pass
            user_id = request.session['id']
            new_author = Authors.authorMgr.addAuthor(request.POST)
            new_book = Books.bookMgr.addBook(request.POST)
            new_review = Reviews.reviewMgr.addReview(request.POST, user_id)
            messages.success(request, 'Book and Review successfully Logged')
            return redirect(reverse("books:index"))
        else:
            for error in validateAll['errors']:
                messages.error(request, error)
            return redirect('books:addForm')

def deleteReview(request):
    pass

def logOut(request):
    request.session.clear()
    return redirect(reverse('users:index'))

def addReview(request, id):
    user_id = request.session['id']
    if request.method == 'POST':
        new_Review = Reviews.reviewMgr.addReview(request.POST, user_id, id)
        messages.success(request, "Review successfully Added")
    #route paramater also requires 'id' which we passed (see show in urls.py)
    #TODO see how to do reverse with paramater
    return redirect(reverse('books:show', args=(id,)))

apps/bookRev/templates/bookRev/addBook.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    {% load staticfiles %}
    <link rel='stylesheet' href="{%static 'bookRev/css/bootstrap.min.css' %}" media="screen" title="bootstrap" charset="utf-8">
  </head>
  <body>
    <div class="container">
     <h2>Add a New Book Title and a Review</h2>
     <div id='bookBox'>
       {% for message in messages %}
          <li{% if message.tags%} class="{{message.tags}}"{%endif%}>{{message}}</li>
       {% endfor %}
       <form action="{% url 'books:newBook' %}" method='POST'>
           {% csrf_token %}
           <p>Book Title: <input type="text" name='title' class='form-control col-md-6'></p>
           <p>Select existing Author:
             <select name='author' type='text'>
               <option> </option>
               {% for x in authors %}
                <option>{{ x.name }}</option>
               {% endfor %}
             </select>
           </p>
           <p>Author: <input type="text" name='author_name' class='form-control col-md-6' ></p>
           <p>Review: <textarea rows="4" cols="50" type="text" name='review' class='form-control col-md-6'></textarea></p>
           <p>Rating:
             <select name='rating'>
               <option value="1"> 1 </option>
               <option value="2"> 2 </option>
               <option value="3"> 3 </option>
               <option value="4"> 4 </option>
               <option value="5"> 5 </option>
             </select>
            </p>
           <input type='submit' value='Create' class="btn btn-default">
       </form>
       <a href="{% url 'books:index' %}"class="btn btn-default">Home</a>
       <a href="{%url 'books:logOut'%}" class="btn btn-default">Log Out</a>
     </div>
   </div>
  </body>
</html>

apps/bookRev/templates/bookRev/bookIndex.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    {% load staticfiles %}
     <link rel='stylesheet' href="{%static 'bookRev/css/bootstrap.min.css' %}" media="screen" title="bootstrap" charset="utf-8">
  </head>
  <body>
    <div class='mainBox'>
      <div class='header container'>
        <h2>Welcome {{ this_user.first_name }}</h2>
        <a href="{% url 'books:addForm' %}" class='btn btn-default'>Add Book and Review</a>
        <a href="{%url 'books:logOut'%}" class="btn btn-default">Log Out</a>
      </div>
      <div class='container'>
        <h3>Other Books with Reviews: </h3>
          <div class='booksBox'>
             {% for book in all_books %}
               <a href="{% url 'books:show' id=book.id%}" class='newLine'>{{ book.title }}</a>
             {% endfor %}
          </div>
      </div>
      <div class='container'>
      {% for message in messages %}
         <h4 class='alert alert-{{ message.tags }}'>{{ message }}</h4>
       {% endfor %}
       <h3>Recent Book Reviews: </h3>
       <div id='recentReviews' class="container">
         {% for review in recent_reviews %}
            <h3><a href="{%url 'books:show' id=review.book.id%}">{{review.book.title}}</a></h3>
            <p> Rating: {{review.rating}}</p>
            <a href="{% url 'books:user' id=review.user.id %}">{{review.user.first_name}}</a>
            <p>says: {{review.review}}</p>
            <p> Posted on {{review.created_at}}</p>
            <hr>
         {% endfor %}
       </div>
     </div>
   </div>
  </body>
</html>

apps/bookRev/templates/bookRev/show.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    {% load staticfiles %}
    <link rel='stylesheet' href="{%static 'bookRev/css/bootstrap.min.css' %}" media="screen" title="bootstrap" charset="utf-8">
  </head>
  <body>
    <div class='container'>
      <a href="{% url 'books:index' %}" class="btn btn-default">Home</a>
      <a href="{% url 'books:logOut'%}" class="btn btn-default">Log Out</a>
    </div>
      <div class='container'>
          <h2>{{ this_book.title }}</h2>
          <h4>Author: {{ this_book.author.name }} </h4>
      </div>
      <div class='container'>
          <h3>Reviews:</h3>
          {% for i in all_reviews %}
            <p>Rating : {{i.rating}}</p>
            <p class='reviewerName'>{{i.user.first_name}} says: </p>
            <p class='review'>{{ i.review }}</p>
            <p>{{i.created_at}}</p>
            <hr>
          {% endfor %}
      </div>
      <div class='container'>
        <form action="{% url 'books:addReview' this_book.id %}" method="POST">
            {% csrf_token %}
            <h3>Add a Review:</h3>
            <input type="hidden" name="book_id" value="{{this_book.id}}">
            <textarea rows="10" cols="50" name='review' class='form-control cold-md-6'></textarea>
            <p>Rating:
              <select name='rating'>
                <option value="1"> 1 </option>
                <option value="2"> 2 </option>
                <option value="3"> 3 </option>
                <option value="4"> 4 </option>
                <option value="5"> 5 </option>
              </select>
             </p>
             <input type='submit' value='Submit Review' class="btn btn-default">
        </form>
      </div>
  </body>
</html>

apps/bookRev/templates/bookRev/user.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    {% load staticfiles %}
    <link rel='stylesheet' href="{%static 'bookRev/css/bootstrap.min.css' %}" media="screen" title="bootstrap" charset="utf-8">
  </head>
  <body>
    <div class='container'>
      <h3>User: {{ this_user.alias }}</h3>
      <h4> Name: {{ this_user.first_name }} {{this_user.last_name}}</h4>
      <p> Email: {{ this_user.email }} </p>
      <p> Total Reviews: {{ this_user.userReviews.count }} </p>
    </div>
    <div class='container'>
      <a href="{% url 'books:index' %}" class="btn btn-default">Home</a>
      <a href="{%url 'books:logOut'%}" class="btn btn-default">Log Out</a>
    </div>
  </body>
</html>